- config: 
    #IRC Server Address
    server: "10.1.1.1"
    #Server Port
    port: "6667"
    #How often should we ping the server to make sure it's alive
    ping: "120"
    #IRC Server Nickname & User
    nick: "robot"
    #What chats should the bot Join?
    channels:
        ["#Team","#Dev"]